name       : haskell-uri-bytestring
version    : 0.2.3.1
release    : 1
source     :
    - http://hackage.haskell.org/package/uri-bytestring-0.2.3.1/uri-bytestring-0.2.3.1.tar.gz : 1d2814b8ca76c8b72fcf995d4d863c492b22bc80c62d990dad2d969cbef1b16d
license    : BSD-3-Clause
component  : programming.haskell
summary    : uri-bytestring aims to be an RFC3986 compliant URI parser that uses efficient ByteStrings for parsing and representing the URI data. 
description: |
    uri-bytestring aims to be an RFC3986 compliant URI parser that uses efficient ByteStrings for parsing and representing the URI data. 
builddeps  :
    - haskell-attoparsec
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-th-lift-instances
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
