name       : haskell-uri-bytestring
version    : 0.3.2.2
release    : 3
source     :
    - https://hackage.haskell.org/package/uri-bytestring-0.3.2.2/uri-bytestring-0.3.2.2.tar.gz : c7d47c25c1dbeae8c80ef7f83095093177e119effa90715a55b15fcaebd8ff6a
license    : BSD-3-Clause
component  : programming.haskell
summary    : uri-bytestring aims to be an RFC3986 compliant URI parser that uses efficient ByteStrings for parsing and representing the URI data.
description: |
    uri-bytestring aims to be an RFC3986 compliant URI parser that uses efficient ByteStrings for parsing and representing the URI data.
builddeps  :
    - haskell-attoparsec-devel
    - haskell-blaze-builder-devel
    - haskell-cabal-install
    - haskell-th-lift-instances-devel
rundeps    :
    - devel:
        - haskell-attoparsec-devel
        - haskell-blaze-builder-devel
        - haskell-th-lift-instances-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
