name       : haskell-uri-bytestring
version    : 0.3.2.0
release    : 2
source     :
    - https://hackage.haskell.org/package/uri-bytestring-0.3.2.0/uri-bytestring-0.3.2.0.tar.gz : acecd68b9d3128d6b6de99580664ab1e7cbaa0e7722e50c5fc67ccbd7c9104e0
license    : BSD-3-Clause
component  : programming.haskell
summary    : uri-bytestring aims to be an RFC3986 compliant URI parser that uses efficient ByteStrings for parsing and representing the URI data.
description: "uri-bytestring aims to be an RFC3986 compliant URI parser that uses efficient ByteStrings for parsing and representing the URI data. \n"
builddeps  :
    - haskell-attoparsec
    - haskell-blaze-builder
    - haskell-cabal-install
    - haskell-th-lift-instances
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
